server:
  port: 80
security:
  basic:
    enabled: false

#解决中文乱码问题
spring:
  http:
    encoding:
      enabled: true
#数据库配置
  datasource:
    primary:
      url: jdbc:mysql://192.168.5.131:3306/activiti?useSSL=false
      username: root
      password: root
      diver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://192.168.5.131:3306/test1?useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 30000
#自动创建表结构
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
#redis配置
  redis:
    database: 0  #数据库索引
    host: localhost   #地址
    port: 6379   #端口
    password:    #默认为空
    pool:
      max-active: 8 #连接池最大连接数
      max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8   #连接池中的最大空闲连接
      min-idle: 0   #连接池中的最小空闲连
    timeout: 0  #连接超时时间（毫秒）

  thymeleaf:
    mode: LEGACYHTML5
    cache: false #页面实现热部署